---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: <your name>
spec:
  # type: LoadBalancer
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
      name: http
  selector:
    app: podinfo
